#!/bin/bash

xmodmap ~/.xmodmap-sid &
cp -r ~/Public/xfcee/ice/xfce4 ~/.config/ &
cp -r Public/nvim_confs/gruv/init.vim  ~/.config/nvim/ & 
xrdb merge ~/Public/xresources/forest/.Xresources & 
picom  &
feh --bg-fill ~/Pictures/wall/autumn.jpg &
cp -r ~/Public/theme\ and\ icons/forest/.gtkrc-2.0 ~/ &
cp -r ~/Public/theme\ and\ icons/forest/settings.ini  ~/.config/gtk-3.0/ &
cp -r ~/Public/rofi/forest/rofi ~/.config/ & 
cp -r Desktop/nvim_confs/gruv/init.vim ~/.config/nvim/ & 
xfce4-panel  &

