#!/bin/bash

cp -r ~/Public/poly/ice/polybar ~/.config/ &
cp -r ~/Public/theme\ and\ icons/icewm/.gtkrc-2.0 ~/ &
cp -r ~/Public/theme\ and\ icons/icewm/settings.ini  ~/.config/gtk-3.0/ &

xrdb merge ~/.Xresources  &
picom  &
feh --bg-fill ~/Pictures/wall/blue.png &
xfce4-panel & 
del .config/nvim && cp -r ~/Public/nvim_confs/base/nvim ~/.config/ & 
~/.config/polybar/launch.sh &
