#!/bin/sh
#
# fluxbox startup-script:

xmodmap ~/.xmodmap-sid & 
picom & 
xrdb merge ~/Public/xresources/ocean/.Xresources & 
feh --bg-fill ~/Pictures/wall/clean.png &
cp -r ~/Public/poly/flux/polybar ~/.config &
sleep 10 && ~/.config/polybar/launch.sh &
exec fluxbox 
