#!/bin/sh
#
# fluxbox startup-script:

xmodmap ~/.xmodmap-sid &  # remove this  
picom & 
xrdb merge ~/.Xresources & 
feh --bg-fill ~/Pictures/wall/clean.png &
sleep 10 && ~/.config/polybar/launch.sh &
exec fluxbox 
