#!/bin/bash


#uncomment the cut option if you are using xorg-xbacklight (line #7)
backlight() {
         backlight="$(xbacklight -get)"
         echo -e "$backlight" #| cut -c 1-2
 }

icon="󰃟 "
 printf "^c#ecf0f1^ $icon"
 printf "%.0f\n" $(backlight)
 

exit 0
