#! /bin/sh

xmodmap ~/.xmodmap-sid &

bspc monitor -d Home Web Work Files Misc

bspc config border_width         1
bspc config window_gap          10
bsp  config presel_feedback_color "#ffffff" 
bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config focused_border_color "#81A1C1"
bspc config normal_border_color "#4F5767" 

# autostart up applications 
cp -r ~/Public/poly/bsp_one/polybar ~/.config/ &
~/.config/polybar/launch.sh &
cp -r ~/Public/theme\ and\ icons/one/.gtkrc-2.0 ~/ &
cp -r ~/Public/theme\ and\ icons/one/settings.ini  ~/.config/gtk-3.0/ &
picom & 
feh --bg-fill ~/Pictures/wall/tri.png &
xrdb merge ~/Public/xresources/ocean/.Xresources &
cp -r ~/Public/rofi/one/rofi/ ~/.config/
bspc config gapless_monocle      true
cp -r ~/Public/nvim_confs/onedark/init.vim ~/.config/nvim/ & 
2bspwm &
sxhkd 

