#!/bin/bash

cp -r ~/Public/xfcee/ice/xfce4 ~/.config/ &

xrdb merge ~/Public/xresources/forest/.Xresources & 
picom  &
feh --bg-fill ~/Pictures/wall/tools.jpg &
cp -r ~/Public/theme\ and\ icons/forest/.gtkrc-2.0 ~/ &
cp -r ~/Public/theme\ and\ icons/forest/settings.ini  ~/.config/gtk-3.0/ &
cp -r ~/Public/rofi/forest/rofi ~/.config/ & 
cp -r Desktop/nvim_confs/gruv/init.vim ~/.config/nvim/ & 
cp -r ~/Public/poly/ice/polybar ~/.config & 
~/.config/polybar/launch.sh 
xfce4-panel  &

