#! /bin/sh

sxhkd &

# polybar theme 
cp -r ~/Public/poly/bsp/polybar/ ~/.config/ &
~/.config/polybar/launch.sh &


cp -r ~/Public/theme\ and\ icons/op/.gtkrc-2.0 ~/
cp -r ~/Public/theme\ and\ icons/op/settings.ini  ~/.config/gtk-3.0/
picom & 
feh --bg-fill ~/Pictures/wall/void.png &
xrdb merge ~/Public/xresources/rea_drac/.Xresources &

cp -r ~/Public/rofi/bspwm/rofi/ ~/.config/


bspc monitor -d I II III IV V VI VII

bspc config border_width         1
bspc config window_gap          6
bsp config presel_feedback_color "#ffffff" 
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc config top_padding 20

bspc config focused_border_color "#A27ED5"
bspc config normal_border_color "#4A4D64"


