#! /bin/sh

xmodmap .xmodmap-sid &

#bspc monitor -d Home Web Work Files Mails Misc
bspc monitor -d 1 2 3 4 5 6

bspc config border_width         3
bspc config window_gap          10
bsp  config presel_feedback_color "#ffffff" 
bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config gapless_monocle      true

#bspc config focused_border_color "#BF616A"
#bspc config normal_border_color "#353b45"

# autostart up applications 
cp -r ~/Public/poly/bsp_one/polybar ~/.config/ &
~/.config/polybar/launch.sh &
cp -r ~/Public/theme\ and\ icons/one/.gtkrc-2.0 ~/ &
cp -r ~/Public/theme\ and\ icons/one/settings.ini  ~/.config/gtk-3.0/ &
picom & 
feh --bg-fill ~/Pictures/wall/bg.png &
xrdb merge ~/Public/xresources/ocean/.Xresources &
cp -r ~/Public/rofi/one/rofi/ ~/.config/
cp -r ~/Public/nvim_confs/onedark/init.vim ~/.config/nvim/ & 

oneDouble &
sxhkd 

