#! /bin/sh

xmodmap ~/.xmodmap-sid &

xrdb merge ~/Public/xresources/forest/.Xresources &
cp -r ~/Public/poly/bsp/polybar/ ~/.config/ &
cp -r ~/Public/theme\ and\ icons/forest/.gtkrc-2.0 ~/
cp -r ~/Public/theme\ and\ icons/forest/settings.ini  ~/.config/gtk-3.0/
picom & 
feh --bg-fill ~/Pictures/wall/gruv_waifu.jpg &
cp -r ~/Public/rofi/forest/rofi/ ~/.config/ &
cp -r ~/Public/nvim_confs/gruv/init.vim  ~/.config/nvim/ & 
~/.config/polybar/launch.sh &

bspc monitor -d Home Web Work Files Mails Misc
#bspc monitor -d I II III IV V VI VII

bspc config border_width         2
bspc config window_gap          10
bsp config presel_feedback_color "#ffffff" 
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc config top_padding 20

bspc config focused_border_color "#83a598"
bspc config normal_border_color "#272A2B"
bspc config gapless_monocle false 
2bspwm &
sxhkd 

