#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

export SESSION=${1:-bspwm}

case $SESSION in
  bsp  ) exec bspwm;;
  flux ) exec startfluxbox;;
  dwm  ) exec dwm;;
  ice  ) exec icewm-session;;
  jwm  ) exec jwm;;
  awe  ) exec awesome;;
  ii   ) exec i3;;
  opp  ) exec openbox-session;;
  dbsp ) exec bspwm -c ~/Public/bspwmConfs/drabspwm;;
      * ) exec $1;;
  esac
