#! /bin/sh

sxhkd &
cp -r ~/Public/theme\ and\ icons/bsp/.gtkrc-2.0 ~/ &
cp -r ~/Public/theme\ and\ icons/bsp/settings.ini ~/.config/gtk-3.0/ &
cp -r ~/Public/poly/bsp/polybar ~/.config/ &
xrdb merge ~/.Xresources &
picom &
feh --bg-fill ~/Pictures/wall/beone.png &
~/.config/polybar/launch.sh &
del .config/nvim && cp -r ~/Public/nvim_confs/base/nvim ~/.config/ &

#oneDouble &
bspc monitor -d 1 2 3 4 5

bspc config border_width 0
bspc config window_gap 15
bsp config presel_feedback_color "#ffffff"
bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc config top_padding 20

bspc config focused_border_color "#545862"
bspc config normal_border_color "#353b45"

bspc config gapless_monocle false
